select Open+Close from Quote_get('IBM');
select Open-Close from Quote_get('IBM');
select Open*Close from Quote_get('IBM');
select Open/Close from Quote_get('IBM');
select Open%Close from Quote_get('IBM');
select Open^Close from Quote_get('IBM');
select Close+*Volume from Quote_get('IBM');
select Volume//Close from Quote_get('IBM');
select Open~Close from Quote_get('IBM');
select (Open>Close)?Day from Quote_get('IBM');
select (Open>Close)? from Quote_get('IBM');
select -Open from Quote_get('IBM');
select Open>Close from Quote_get('IBM');
select Open>=Close from Quote_get('IBM');
select Open<Close from Quote_get('IBM');
select Open<=Close from Quote_get('IBM');
select Open=Close from Quote_get('IBM');
select Open<>Close from Quote_get('IBM');
select (Open>=Close) & (High<>Low) from Quote_get('IBM');
select (Open>Close) | (High=Low) from Quote_get('IBM');
select (Open=Close) # (High=Low) from Quote_get('IBM');
select !(Open=Close) from Quote_get('IBM');
select ~Volume from Quote_get('IBM');
select Volume & 1 from Quote_get('IBM');
select Volume | 1 from Quote_get('IBM');
select Volume # -1 from Quote_get('IBM');
select @(Open-Close) from Quote_get('IBM');
select Day,Open||Close from Quote_get('IBM', date('01-Nov-2013'), date('03-Nov-2013'));
select cs_maxof(Open,Close) from Quote_get('IBM');
select cs_minof(Open,Close) from Quote_get('IBM');
select cs_norm(Close) from Quote_get('IBM');
select Close*'{2.0,2.1,2.2}'::text from Quote_get('IBM', '1-Nov-2013', '4-Nov-2013');
select Close*'float4:{2.0,2.1,2.2}' from Quote_get('IBM', '1-Nov-2013', '4-Nov-2013');
select Day=date('1-Nov-2013') from Quote_get('IBM');
select Volume*2 from Quote_get('ABB');
select cs_parse('{1,2,3,4}','int4')+cs_const(3.14,'float4');
select cs_parse('{1,2,3,4}','int4')+10;
select cs_parse('{1,2,3,4}', 'int4')+'{10,20,30,40}'::text;
select cs_parse('{11-Nov-2013,12-Nov-2013,30-Nov-2013}', 'date');
select cs_concat('int4:{1,2,3}','int4:{4,5,6}');
select cs_parse('{1,2,3,4,5}', 'int4') << 1;
select cs_parse('{1,2,3,4,5}', 'int4') >> 2;
select cs_parse('{1,2,3,4,5}', 'int4') << 10;
select cs_parse('{1,2,3,4,5}', 'int4') >> 10;
select cs_like('bpchar8:{Abc,aaBcc,aabbcc,abcba,aabbabcc,aabac,bca}', '%abc%');
select cs_ilike('bpchar8:{Abc,aaBcc,aabbcc,abcba,aabbabcc,aabac,bca}', '%abc%');
select cs_parse('{Abc,aaBcc,aabbcc,abcba,aabbabcc,aabac,bca}', 'bpchar', 8) ~~ '%abc%';
